package com.josephcatrambone.debatesimulator

enum class Topic {
	NO_TOPIC,
	ABORTION,
	BUDGET_AND_ECONOMY,
	CIVIL_RIGHTS,
	CORPORATIONS,
	CRIME,
	DRUGS,
	EDUCATION,
	ENERGY_AND_OIL,
	ENVIRONMENT,
	FAMILIES_AND_CHILDREN,
	FOREIGN_POLICY,
	FREE_TRADE,
	GOVERNMENT_REFORM,
	GUN_CONTROL,
	HEALTHCARE,
	HOMELAND_SECURITY,
	IMMIGRATION,
	INFRASTRUCTURE_AND_TECHNOLOGY,
	JOBS,
	PRINCIPLES_AND_VALUES,
	SOCIAL_SECURITY,
	TAX_REFORM,
	WAR_AND_PEACE,
	WELFARE_AND_POVERTY
}